'use client'

import { useParams, useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import { collection, getDocs, query, where } from 'firebase/firestore'
import { db } from '../../lib/firebase'
import { useAuth } from '../../contexts/AuthContext'
import { Award, Flame, GamepadIcon, GitFork, HelpCircle, Hourglass, Key, MapPin, Trophy, User, Settings, Edit } from 'lucide-react'
import FriendRequestButton from '../../components/FriendRequestButton'
import FollowButton from '../../components/FollowButton'
import PrivacySettingsModal from '../../components/PrivacySettingsModal'
import FollowList from '../../components/FollowList'
import NotificationsPanel from '../../components/NotificationsPanel'
import ProfileEdit from '../../components/ProfileEdit'
